workspace 'ZP_Base.xcworkspace'

def shared_pods
    pod 'AFNetworking'
end


target 'ZP_Base' do
    xcodeproj 'ZP_Base.xcodeproj'
    shared_pods
end

target 'Exc001' do
    xcodeproj 'Exc001/Exc001.xcodeproj'
    shared_pods
end


