workspace 'ZP_Base.xcworkspace'

use_frameworks!

platform :ios, '8.0'

def shared_pods
    pod 'AFNetworking'
    pod 'Masonry'
end


def swift_pods
    pod 'SnapKit'
end



target 'ZP_Base' do
    project 'ZP_Base.xcodeproj'
    shared_pods
end

target 'Exc001' do
    project 'Exc001/Exc001.xcodeproj'
    shared_pods
end

target 'BaiduExs' do
    project 'BaiduExs/BaiduExs.xcodeproj'
    shared_pods
    pod 'BaiduMapKit','3.2'
end

target 'JSPatchExc' do
    project 'JSPatchExc/JSPatchExc.xcodeproj'
    shared_pods
    pod 'JSPatch'
end




target 'SwiftExs' do
    project 'SwiftExs/SwiftExs.xcodeproj'
    swift_pods
end




    


    




