workspace 'ZP_Base.xcworkspace'

def shared_pods
    pod 'AFNetworking'
    pod 'JSPatch'
    pod 'Masonry'
end


target 'ZP_Base' do
    xcodeproj 'ZP_Base.xcodeproj'
    shared_pods
end

target 'Exc001' do
    xcodeproj 'Exc001/Exc001.xcodeproj'
    shared_pods
end

target 'JSPatchExc' do
    xcodeproj 'JSPatchExc/JSPatchExc.xcodeproj'
    shared_pods
    
target 'TestReactiveNativeAuto' do
    xcodeproj 'TestReactiveNativeAuto/ios／TestReactiveNativeAuto.xcodeproj'
    shared_pods
    
#pod 'React', :path => 'TestReactiveNative/ReactNative',
#:subspecs => [
#'Core',
#'RCTActionSheet',
#'RCTAdSupport',
#'RCTGeolocation',
#'RCTImage',
#'RCTNetwork',
#'RCTPushNotification',
#'RCTSettings',
#'RCTText',
#'RCTVibration',
#'RCTWebSocket',
#'RCTLinkingIOS'
#]

    

end


